### ISSUE TITLE
Setting strict mode to false returns null

### ISSUE THREAD

**Issue by ssalihu** [DopplerLabs/serverless-plugin-aws-resolvers#55]
Hello! 
I am trying to use the plugin by setting **strict** to false. The setup works in my existing configuration. I have a new requirement to set ARN value and it appears that ARN cannot take null or undefined. 

I was hoping that the below setup would return 'not created yet' if the resolver fails and if the strict mode is false.

```
custom:
  awsResolvers:
    strict: false
  dynamodbArn: ${aws:dynamodb:my_db_name:LatestStreamArn, 'not created yet'}
```

But instead, returns null (src/index.js).

```

 if (strictMode) {
          throw e
        }
  winston.debug(`Error while resolving ${variableString}: ${e.message}`)
  return null
```

I am encountering this challenge when using the below serverless config

```
handler:
    name: something
    handler: src/something/somthing.function
    events:
      - stream: ${self:custom.dynamodbArn}  # works 
      - stream: 
          type: dynamodb 
          arn: ${self:custom.dynamodbArn} # does not work problem is here since it returns null
          batchSize: 1
```
Error:
```
TypeError: Cannot read property 'Fn::GetAtt' of null
```
I would like to return the default value that was set instead of null. Any ideas? Thank you!!!
